name: SilentWatch
version: 1.0
main: me.maro.silentwatch.Main
api-version: 1.21

commands:
  watch:
    description: Watch player silently
    usage: /watch <player>
    permission: silentwatch.use
  watchoff:
    description: Exit watch mode
    usage: /watchoff
    permission: silentwatch.use

permissions:
  silentwatch.use:
    default: op
